### ISSUE TITLE
Same Prev/Next post and wrong title showing up!

### ISSUE THREAD

**Issue by YoucefHQ** [goranefbl/swifty-bar#7]
Hey!

I wanted to run an A/B test on Welovebuzz.com to see how Swifty Bar performs in terms of shares compared to the custom solution we use.

Unfortunately, the plugin always shows:
- The same Prev/Next post (Next http://www.welovebuzz.com/sky-pool-la-piscine-reliant-deux-immeubles-londoniens/ and Prev http://www.welovebuzz.com/elle-affiche-son-corps-couvert-a-70-par-des-taches-de-naissance/)
- The wrong title (This title http://www.welovebuzz.com/les-7-signes-qui-font-de-toi-une-personne-sapiosexuelle/ but when share it on Facebook or Twitter, it has the right title/link)

It seems that that another user of the plugin had the same issue: https://wordpress.org/support/topic/prevnext-posts-showing-the-same-posts-for-all-posts

About Welovebuzz:
- Last version of Wordpress
- Theme done from scratch
- No weird plugins/functions, we use the classical WP ones

Thanks!

**Comment by goranefbl** [comment]
Hey Technologix, thanks for the patch. Ill pull it now, it looks like more of a prevention if theme did not reset query after its custom query.

Thanks
